### ISSUE TITLE
No issue, just want to say thank you!

### ISSUE THREAD

**Issue by HotdogWang** [tomtcy1989/Hackintosh-Z490M-OpenCore#1]
Thanks a lot.
You save me a lot of times.

**Comment by tomtcy1989** [comment]
> Thanks a lot.
> You save me a lot of times.

Thank you for your kind feedback Mr Wang. Feel free to update to the latest builds from https://dortania.github.io/builds/

For the record, the formal monthly builds will release tomorrow 08 Dec 2020 morning (Melbourne Australia where I am).

**Comment by HotdogWang** [comment]
One more question, just update kext or...?

What's the step you suggestion? because I'm a new comer about opencore.

Thanks for your reply.

**Comment by tomtcy1989** [comment]
> One more question, just update kext or...?
> 
> What's the step you suggestion? because I'm a new comer about opencore.
> 
> Thanks for your reply.

Pleasure. I generally update to the latest builds for both kexts and OpenCore. I have never experienced any issues updating to the latest builds.

https://dortania.github.io/OpenCore-Post-Install/universal/update.html This is what I follow. Replacing files part is easy - just drag and drop in the existing EFI folder (back up to a USB first if you don't have a second computer to boot into macOS to recover EFI folder). The trickier part is to use OCConfigCompare to transfer new entries from the latest Sample.plist to your config.plist to make sure any new quirks are properly enabled/disabled.

**Comment by HotdogWang** [comment]
Thanks for your sharing.😁
